[mpd]
address = "localhost:6600"

[colors]
album = "#26a0a1"
artist = "#d67751"
song_title = "#fae280"
border = "#fae280"
border_title = "#8193af"
playing = "#fae280"
paused = "#fae280"
stopped = "#fae280"
progress_filled = "#26a0a1"
progress_empty = "#1b1d0e"
time_elapsed = "#c6bb69"
time_separator = "#c6bb69"
time_duration = "#c6bb69"
